#!/usr/bin/expect

#set filename ~/Dropbox/ctf/services/rpi/badlogger.exe
set filename ~/Dropbox/ctf/services/rpi/badlogger.exe.patch_stack_ovf.larger_malloc.patch_signed_comprasion.patch_modulo_10

spawn nc 10.5.8.3 8989
expect {
  "HELLO\r\n" {
    send "KILL\r"
    exp_continue
  }
  "KILLED\r\n" {}
  timeout {
    puts error
    exit 1
  }
}

spawn lftp 10.5.8.3
expect {
  "transferred\r\n" {}
  -re {553[^\r]*\n} exp_continue
  -re {lftp[^\r]*> } {
    send "put $filename -o badlogger.exe\r"
    sleep 1
    exp_continue
  }
}

spawn nc 10.5.8.3 8989
expect {
  "HELLO\r\n" {
    send "START\r"
    exp_continue
  }
  STARTED {send_user "\n"}
  timeout {
    puts error
    exit 1
  }
}
